#!/bin/sh

grade0=0
grade0max=20
./test0 && grade0=`expr $grade0 "+" 20`

grade1=0
grade1max=20
./test1 && grade1=`expr $grade1 "+" 20`

grade2=0
grade2max=20
./test2 && grade2=`expr $grade2 "+" 20`

grade3=0
grade3max=20
./test3 && grade3=`expr $grade3 "+" 20`

grade4=0
grade4max=20
./test4 && grade4=`expr $grade4 "+" 20`

total=`expr $grade0 + $grade1 + $grade2 + $grade3 + $grade4`

totalmax=`expr $grade0max + $grade1max + $grade2max + $grade3max + $grade4max`

echo   "-------------------------------------------------"
echo   "User:  $1 "
echo   "-------------------------------------------------"
printf "Test0:          	 %-3d%s%-3d\n" $grade0 " of " $grade0max
printf "Test1:          	 %-3d%s%-3d\n" $grade1 " of " $grade1max
printf "Test2:                   %-3d%s%-3d\n" $grade2 " of " $grade2max
printf "Test3:                   %-3d%s%-3d\n" $grade3 " of " $grade3max
printf "Test4:                   %-3d%s%-3d\n" $grade4 " of " $grade4max
echo   "--------------------------------------------------"
printf "Total:                   %-3d%s%-3d\n" $total " of " $totalmax

